openapi: 3.0.1
info:
  title: Configurazione weModI versione v1
  description: API per la configurazione di Fruizioni ed Erogazioni del modulo weModI
    e caricamento dei relativi certificati di firma
  version: v1
servers:
- url: /api/am/wemodi/v1
  description: Base path URL
paths:
  /configurationservice/aliasWithThumbprint:
    get:
      operationId: getAliasWithThumbprint
      parameters:
      - name: thumbprint
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/applicationUUIDByKid:
    get:
      operationId: getApplicationUUIDByKid
      parameters:
      - name: kidPdndApi
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/applicationsCreatedByUser:
    get:
      operationId: getApplicationsCreatedByUser
      parameters:
      - name: userName
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/applicationsCreators:
    get:
      operationId: getAllApplicationsCreators
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/applicationsFromSameOrg:
    get:
      operationId: getApplicationsFromSameOrg
      parameters:
      - name: userName
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/cacheConfigurations:
    get:
      operationId: getCacheConfigurations
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/certificate/{tableName}/{clauseName}/{clauseValue}:
    delete:
      operationId: deleteCertificate
      parameters:
      - name: tableName
        in: path
        required: true
        schema:
          type: string
      - name: clauseName
        in: path
        required: true
        schema:
          type: string
      - name: clauseValue
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            '*/*': {}
  /configurationservice/certificateInbound:
    post:
      operationId: insertCertificateInbound
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/certificateOutboundModi/{appUUID}:
    post:
      operationId: insertCertificateOutboundModi
      parameters:
      - name: appUUID
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/certificateOutboundPdnd/{appUUID}:
    post:
      operationId: insertCertificateOutboundPdnd
      parameters:
      - name: appUUID
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/certificateSOAP:
    get:
      operationId: getCertificateSOAP
      parameters:
      - name: firstKeyIdentifier
        in: query
        schema:
          type: string
      - name: secondKeyIdentifier
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/certificateSOAPInbound:
    post:
      operationId: insertCertificateSOAPInbound
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/certificateSOAPOutbound/{appUUID}:
    post:
      operationId: insertCertificateSOAPOutboundModi
      parameters:
      - name: appUUID
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/certificatesInbound:
    get:
      operationId: getCertificatesInboundModi
      parameters:
      - name: applicationUUID
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/certificatesOutboundModi:
    get:
      operationId: getCertificatesOutboundModi
      parameters:
      - name: applicationUUID
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/certificatesOutboundPdnd:
    get:
      operationId: getCertificatesOutboundPdnd
      parameters:
      - name: applicationUUID
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/certificatesSOAPInbound:
    get:
      operationId: getCertificatesSOAPInboundModi
      parameters:
      - name: applicationUUID
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/certificatesSOAPOutbound:
    get:
      operationId: getCertificatesSOAPOutboundModi
      parameters:
      - name: applicationUUID
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/privateKeyByConsumerKeyForModi:
    get:
      operationId: getPrivateKeyByConsumerKeyForModi
      parameters:
      - name: consumerKey
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/privateKeyByConsumerKeyForPdnd:
    get:
      operationId: getPrivateKeyByConsumerKeyForPdnd
      parameters:
      - name: consumerKey
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/privateKeyByConsumerKeyForSOAP:
    get:
      operationId: getPrivateKeyByConsumerKeyForSOAP
      parameters:
      - name: consumerKey
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/subscriptionDetails:
    get:
      operationId: getSubscriptionDetails
      parameters:
      - name: subscriptionUUID
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /configurationservice/subscriptionDetails/{subscriptionUUID}:
    post:
      operationId: insertSubscriptionMappingPdnd
      parameters:
      - name: subscriptionUUID
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PdndPKMapping'
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /swagger.yaml:
    get:
      operationId: swaggerYamlGet
      responses:
        default:
          description: default response
          content:
            text/yaml: {}
components:
  schemas:
    CertAppMapping:
      type: object
      properties:
        alias:
          type: string
        applicationCreator:
          type: string
        applicationName:
          type: string
        applicationUUID:
          type: string
        certHash:
          type: string
        certificate:
          type: string
        issuerDN:
          type: string
        issuerName:
          type: string
        pdndClientId:
          type: string
        pdndKidApiInterop:
          type: string
        pdndPublicKey:
          type: string
        pdndPurposeId:
          type: string
        serialNumber:
          type: string
        subjectKeyIndentifier:
          type: string
        thumbprint:
          type: string
        thumbprintSha256:
          type: string
        valid:
          type: boolean
    ModiPKMapping:
      type: object
      properties:
        alg:
          type: string
        applicationUUID:
          type: string
        aud:
          type: string
        certificate:
          type: string
        enabled:
          type: boolean
        iss:
          type: string
        kid:
          type: string
        privkey:
          type: string
        publickey:
          type: string
        sub:
          type: string
        typ:
          type: string
        wsaddressingTo:
          type: string
    PdndPKMapping:
      type: object
      properties:
        alg:
          type: string
        applicationUUID:
          type: string
        aud:
          type: string
        clientId:
          type: string
        enabled:
          type: boolean
        iss:
          type: string
        keyType:
          type: string
        kid:
          type: string
        privkey:
          type: string
        purposeId:
          type: string
        scope:
          type: string
        sub:
          type: string
        typ:
          type: string
        uri:
          type: string
